apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonatype-registry
  namespace: nexus
  labels:
    app: sonatype-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonatype-registry
  template:
    metadata:
      labels:
        app: sonatype-registry
    spec:
      containers:
        - image: sonatype/nexus3
          name: nexus
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: sonatype-service
  namespace: nexus
spec:
  ports:
    - name: sonatype-registry
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: sonatype-registry
  type: LoadBalancer