apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cm
  namespace: accounting
  labels:
    app: backend
data:
  COMMUNICATION_INITIATE_ENABLED: "false"
  COMMUNICATION_FORWARD_ENABLED: "true"
  COMMUNICATION_FORWARD_TARGET_URL: "http://persistence:8080"