apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
  namespace: accounting
  labels:
    app: frontend
data:
  COMMUNICATION_INITIATE_ENABLED: true
  COMMUNICATION_INITIATE_TARGET_URL: "backend:8080"
  COMMUNICATION_FORWARD_ENABLED: false