apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: accounting
  name: restrict-access-to-frontend
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: backend