replicaCount: 1

image:
  repository: davidmachacek/testapp
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.4"

networkPolicy:
  create:
    restrictAccessToBackend: true
    restrictAccessToPersistence: true
    restrictAccessBetweenNamespaces: true