apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
data:
  COMMUNICATION_INITIATE_ENABLED: "{{ .Values.backend.initiate.enabled }}"
  COMMUNICATION_INITIATE_TARGET_URL: "{{ .Values.backend.initiate.host }}"
  COMMUNICATION_FORWARD_ENABLED: "{{ .Values.backend.forward.enabled }}"
  COMMUNICATION_FORWARD_TARGET_URL: "{{ .Values.backend.forward.host }}"
  APP_ENVIRONMENT: "{{ .Values.environment }}"