apiVersion: v1
kind: ConfigMap
metadata:
  name: persistence-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: persistence
data:
  COMMUNICATION_INITIATE_ENABLED: "{{ .Values.persistence.initiate.enabled }}"
  COMMUNICATION_INITIATE_TARGET_URL: "{{ .Values.persistence.initiate.host }}"
  COMMUNICATION_FORWARD_ENABLED: "{{ .Values.persistence.forward.enabled }}"
  COMMUNICATION_FORWARD_TARGET_URL: "{{ .Values.persistence.forward.host }}"
  APP_ENVIRONMENT: "{{ .Values.environment }}"