apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
data:
  COMMUNICATION_INITIATE_ENABLED: "{{ .Values.frontend.initiate.enabled }}"
  COMMUNICATION_INITIATE_TARGET_URL: "{{ .Values.frontend.initiate.host }}"
  COMMUNICATION_FORWARD_ENABLED: "{{ .Values.frontend.forward.enabled }}"
  COMMUNICATION_FORWARD_TARGET_URL: "{{ .Values.frontend.forward.host }}"