apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: persistence
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: persistence
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configMap-persistence.yaml") . | sha256sum }}
      labels:
        app: persistence
    spec:
      containers:
        - name: testapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: persistence-cm

