{{- if .Values.networkPolicy.create.restrictAccessToBackend -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: restrict-access-to-backend
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
        - podSelector:
            matchLabels:
              app: persistence
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: backend
    - to:
        - podSelector:
            matchLabels:
              app: persistence
{{- end }}