apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: restrict-access-to-frontend
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Egress
    - Ingress
  ingress:
    {{- if .Values.networkPolicy.create.restrictAccessToFrontend -}}
    - from:
        - podSelector:
            matchLabels:
              app: backend
    {{- else }}
    - {}
    {{- end }}
  egress:
    {{- if .Values.networkPolicy.create.restrictAccessToFrontend -}}
    - to:
        - podSelector:
            matchLabels:
              app: backend
    {{- else }}
    - {}
    {{- end }}
