apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: restrict-access-to-frontend
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - from:
        {{- if .Values.networkPolicy.create.restrictAccessToFrontend -}}
        - podSelector:
            matchLabels:
              app: backend
        {{- else }}
        - {}
        {{- end }}
  egress:
    - to:
        {{- if .Values.networkPolicy.create.restrictAccessToFrontend -}}
        - podSelector:
            matchLabels:
              app: backend
        {{- else }}
        - {}
        {{- end }}
